
-- Project table
CREATE TABLE `project` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(30) NOT NULL DEFAULT '0',
	`description` VARCHAR(140) NOT NULL DEFAULT '0',
	`start_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`deadline` TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;


-- Draft table
CREATE TABLE `draft` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`project_id` INT(11) NOT NULL DEFAULT '0',
	`draft_version` INT(11) NOT NULL DEFAULT '0',
	`headings` TEXT NOT NULL DEFAULT '0',
	`description` VARCHAR(140) NULL DEFAULT '0',
	`file` TEXT NOT NULL DEFAULT '0',
	`date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;


-- Account table
CREATE TABLE `account` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(10) NOT NULL,
	`email` VARCHAR(50) NOT NULL,
	`password` TEXT NOT NULL,
	`date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
